import { StyleSheet } from 'react-native';

export const colors = {
  white: '#FFFFFF',
  black: '#000000',
  red: '#E53E3E',
  gray: '#999999',
  lightGray: '#F5F5F5',
  borderGray: '#E0E0E0',
  blue: '#007AFF',
  darkGray: '#666666',
};

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: 8,
    width: '100%',
    maxWidth: 400,
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
  },
  closeButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: colors.lightGray,
  },
  closeButtonText: {
    fontSize: 20,
    color: colors.black,
    fontWeight: 'bold',
  },
  modalContent: {
    maxHeight: '100%',
  },
  modalContentContainer: {
    padding: 20,
    flexGrow: 1,
    paddingBottom: 40,
  },
  step2Container: {
    minHeight: '100%',
  },
  stepIndicator: {
    marginBottom: 20,
    alignItems: 'center',
  },
  stepContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    backgroundColor: colors.red,
  },
  stepCircleInactive: {
    backgroundColor: colors.lightGray,
  },
  stepNumber: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  stepNumberActive: {
    color: colors.white,
  },
  stepNumberInactive: {
    color: colors.gray,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: colors.borderGray,
    marginHorizontal: 10,
  },
  stepInstruction: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.black,
    marginTop: 20,
    marginBottom: 15,
    textAlign: 'left',
  },
  inputContainer: {
    marginBottom: 20,
  },
  textInput: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 16,
    color: colors.black,
  },
  textInputError: {
    borderBottomColor: colors.red,
  },
  readOnlyInput: {
    backgroundColor: colors.lightGray,
    color: colors.darkGray,
    borderBottomColor: colors.borderGray,
  },
  infoText: {
    fontSize: 14,
    color: colors.darkGray,
    lineHeight: 20,
    marginBottom: 30,
    textAlign: 'center',
  },
  formContainer: {
    marginBottom: 30,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputGroupHalf: {
    flex: 1,
    marginRight: 10,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
    marginBottom: 8,
  },
  inputLabelError: {
    color: colors.red,
  },
  errorText: {
    fontSize: 12,
    color: colors.red,
    marginTop: 4,
  },
  optionalLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.gray,
    fontStyle: 'italic',
  },
  checkboxRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colors.borderGray,
    borderRadius: 3,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButton: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colors.borderGray,
    borderRadius: 10,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  checkmark: {
    color: colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.white,
  },
  checkboxText: {
    fontSize: 14,
    color: colors.black,
    lineHeight: 20,
    marginLeft: 8,
  },
  redText: {
    color: colors.red,
    fontWeight: 'bold',
  },
  selectButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  selectButtonText: {
    fontSize: 16,
    flex: 1,
  },
  selectButtonTextSelected: {
    color: colors.black,
  },
  selectButtonTextPlaceholder: {
    color: colors.gray,
  },
  selectArrow: {
    fontSize: 12,
    color: colors.gray,
    marginLeft: 10,
  },
  selectButtonDisabled: {
    backgroundColor: colors.lightGray,
    opacity: 0.6,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  backButton: {
    flex: 1,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderGray,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginRight: 10,
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.black,
    fontSize: 14,
    fontWeight: '500',
  },
  exitButton: {
    flex: 1,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderGray,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginRight: 10,
    alignItems: 'center',
  },
  exitButtonText: {
    color: colors.black,
    fontSize: 12,
    fontWeight: '500',
  },
  continueButton: {
    flex: 1,
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginLeft: 10,
    alignItems: 'center',
  },
  continueButtonDisabled: {
    backgroundColor: colors.gray,
  },
  continueButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  finishButton: {
    flex: 1,
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginLeft: 10,
    alignItems: 'center',
  },
  finishButtonDisabled: {
    backgroundColor: colors.gray,
  },
  finishButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  selectionModal: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 20,
    width: '90%',
    maxWidth: 500,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  selectionModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 20,
  },
  selectionScrollView: {
    maxHeight: 440, // Altura para aproximadamente 8 elementos (55px cada uno)
  },
  selectionOption: {
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
  },
  selectionOptionText: {
    fontSize: 16,
    color: colors.black,
    textAlign: 'center',
  },
  selectionCancelButton: {
    marginTop: 15,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: colors.lightGray,
    borderRadius: 6,
    alignItems: 'center',
  },
  selectionCancelButtonText: {
    fontSize: 14,
    color: colors.black,
    fontWeight: '500',
  },
  textInputError: {
    borderBottomColor: colors.red,
    borderBottomWidth: 2,
  },
  successText: {
    fontSize: 12,
    color: '#10B981',
    marginTop: 6,
    fontWeight: '500',
  },
  accountFoundModal: {
    backgroundColor: colors.white,
    borderRadius: 8,
    width: '100%',
    maxWidth: 400,
    padding: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  accountFoundTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 10,
  },
  accountFoundSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.red,
    textAlign: 'center',
    marginBottom: 20,
  },
  accountFoundContent: {
    marginBottom: 30,
  },
  accountFoundText: {
    fontSize: 14,
    color: colors.darkGray,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 15,
  },
  accountFoundButton: {
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  accountFoundButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  registrationSuccessModal: {
    backgroundColor: colors.white,
    borderRadius: 8,
    width: '100%',
    maxWidth: 400,
    padding: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
    zIndex: 9999,
  },
  registrationSuccessTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#10B981',
    textAlign: 'center',
    marginBottom: 20,
  },
  registrationSuccessContent: {
    marginBottom: 30,
  },
  registrationSuccessText: {
    fontSize: 15,
    color: colors.darkGray,
    lineHeight: 24,
    textAlign: 'center',
  },
  registrationSuccessButton: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  registrationSuccessButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
});
