import { StyleSheet } from 'react-native';

export const colors = {
  white: '#FFFFFF',
  black: '#000000',
  red: '#E53E3E',
  gray: '#999999',
  lightGray: '#F5F5F5',
  borderGray: '#E0E0E0',
  blue: '#007AFF',
};

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: 5,
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    flex: 1,
  },
  closeButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: colors.lightGray,
  },
  closeButtonText: {
    fontSize: 20,
    color: colors.black,
    fontWeight: 'bold',
  },
  modalContent: {
    padding: 20,
  },
  descriptionText: {
    fontSize: 14,
    color: colors.black,
    lineHeight: 20,
    marginBottom: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.black,
    marginBottom: 8,
  },
  textInput: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 16,
    color: colors.black,
  },
  selectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
    paddingVertical: 12,
  },
  selectInput: {
    flex: 1,
    fontSize: 16,
    color: colors.black,
    paddingRight: 10,
  },
  dropdownIcon: {
    fontSize: 16,
    color: colors.gray,
    marginLeft: 8,
  },
  resetButton: {
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  resetButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  resetButtonDisabled: {
    backgroundColor: colors.gray,
    opacity: 0.6,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 10,
  },
  loadingText: {
    fontSize: 14,
    color: colors.gray,
    marginLeft: 10,
  },
  errorText: {
    fontSize: 14,
    color: colors.red,
    paddingVertical: 12,
  },
  hintText: {
    fontSize: 12,
    color: colors.gray,
    paddingTop: 8,
    fontStyle: 'italic',
  },
  buildingsListContainer: {
    marginTop: 8,
  },
  buildingsCountText: {
    fontSize: 12,
    color: colors.gray,
    marginBottom: 8,
    fontWeight: '500',
  },
  buildingsList: {
    maxHeight: 200,
    borderWidth: 1,
    borderColor: colors.borderGray,
    borderRadius: 5,
  },
  buildingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
    backgroundColor: colors.white,
  },
  buildingItemSelected: {
    backgroundColor: '#FFF5F5',
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.red,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioCircleInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.red,
  },
  buildingInfo: {
    flex: 1,
  },
  buildingName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
    marginBottom: 4,
  },
  buildingRef: {
    fontSize: 12,
    color: colors.gray,
  },
});
